// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_homelab

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func HomelabProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type HomelabModel struct {
}
